"""add tool file

Revision ID: 4823da1d26cf
Revises: 053da0c1d756
Create Date: 2024-01-15 11:37:16.782718

"""
import sqlalchemy as sa
from alembic import op

from core.sqltype import UUID, gen_uuid

# revision identifiers, used by Alembic.
revision = '4823da1d26cf'
down_revision = '053da0c1d756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_files',
                    sa.Column('id', UUID, default=gen_uuid, nullable=False, comment='ID'),
                    sa.Column('user_id', UUID, nullable=False, comment='用户ID'),
                    sa.Column('tenant_id', UUID, nullable=False, comment='租户ID'),
                    sa.Column('conversation_id', UUID, nullable=False, comment='会话ID'),
                    sa.Column('file_key', sa.String(length=255), nullable=False, comment='key'),
                    sa.Column('mimetype', sa.String(length=255), nullable=False, comment='类型'),
                    sa.Column('original_url', sa.String(length=255), nullable=True, comment='原始URL'),
                    sa.PrimaryKeyConstraint('id', name='tool_file_pkey')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tool_files')
    # ### end Alembic commands ###
