"""add tool providers

Revision ID: 7ce5a52e4eee
Revises: 2beac44e5f5f
Create Date: 2023-07-10 10:26:50.074515

"""
import sqlalchemy as sa
from alembic import op

from core import sqltype
from core.sqltype import UUID

# revision identifiers, used by Alembic.
revision = '7ce5a52e4eee'
down_revision = '2beac44e5f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_providers',
                    sa.Column('id', UUID(), nullable=False, comment='ID'),
                    sa.Column('tenant_id', UUID(), nullable=False, comment='租户ID'),
                    sa.Column('tool_name', sa.String(length=40), nullable=False, comment='工具名称'),
                    sa.Column('encrypted_credentials', sa.String(length=4096), nullable=True,
                              server_default=sqltype.empty_text(), comment='加密凭证'),
                    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False,
                              comment='是否启用'),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False, comment='创建时间'),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False, comment='更新时间'),
                    sa.PrimaryKeyConstraint('id', name='tool_provider_pkey'),
                    sa.UniqueConstraint('tenant_id', 'tool_name', name='unq_tool_provider_tool_name')
                    )
    with op.batch_alter_table('app_model_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sensitive_word_avoidance', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_model_configs', schema=None) as batch_op:
        batch_op.drop_column('sensitive_word_avoidance')

    op.drop_table('tool_providers')
    # ### end Alembic commands ###
