"""add_api_based_extension

Revision ID: 968fff4c0ab9
Revises: b3a09c049e8e
Create Date: 2023-10-27 13:05:58.901858

"""
import sqlalchemy as sa
from alembic import op

from core.sqltype import UUID

# revision identifiers, used by Alembic.
revision = '968fff4c0ab9'
down_revision = 'b3a09c049e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('api_based_extensions',
                    sa.Column('id', UUID(), nullable=False, comment='ID'),
                    sa.Column('tenant_id', UUID(), nullable=False, comment='租户ID'),
                    sa.Column('name', sa.String(length=255), nullable=False, comment='名字'),
                    sa.Column('api_endpoint', sa.String(length=255), nullable=False, comment='api端点'),
                    sa.Column('api_key', sa.String(length=2048), nullable=False, comment='api key'),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False, comment='创建时间'),
                    sa.PrimaryKeyConstraint('id', name='api_based_extension_pkey')
                    )
    with op.batch_alter_table('api_based_extensions', schema=None) as batch_op:
        batch_op.create_index('idx_idx_api_based_extension_tenant', ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('api_based_extensions', schema=None) as batch_op:
        batch_op.drop_index('api_based_extension_tenant_idx')

    op.drop_table('api_based_extensions')

    # ### end Alembic commands ###
