"""add external_data_tools in app model config

Revision ID: a9836e3baeee
Revises: 968fff4c0ab9
Create Date: 2023-11-02 04:04:57.609485

"""
import sqlalchemy as sa
from alembic import op

from core import sqltype

# revision identifiers, used by Alembic.
revision = 'a9836e3baeee'
down_revision = '968fff4c0ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_model_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_data_tools', sa.String(length=1024), nullable=True,
                                      server_default=sqltype.empty_text(), comment='外部数据工具'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_model_configs', schema=None) as batch_op:
        batch_op.drop_column('external_data_tools')

    # ### end Alembic commands ###
