"""add provider order

Revision ID: bf0aec5ba2cf
Revises: e35ed59becda
Create Date: 2023-08-10 00:03:44.273430

"""
import sqlalchemy as sa
from alembic import op

from core import sqltype
from core.sqltype import UUID

# revision identifiers, used by Alembic.
revision = 'bf0aec5ba2cf'
down_revision = 'e35ed59becda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_orders',
                    sa.Column('id', UUID(), nullable=False, comment='ID'),
                    sa.Column('tenant_id', UUID(), nullable=False, comment='租户ID'),
                    sa.Column('provider_name', sa.String(length=40), nullable=False, comment='提供方名字'),
                    sa.Column('account_id', UUID(), nullable=False, comment='账号ID'),
                    sa.Column('payment_product_id', sa.String(length=191), nullable=False, comment='支付产品ID'),
                    sa.Column('payment_id', sa.String(length=191), nullable=True, server_default=sqltype.empty_text(),
                              comment='支付ID'),
                    sa.Column('transaction_id', sa.String(length=191), nullable=True,
                              server_default=sqltype.empty_text(), comment='交易ID'),
                    sa.Column('quantity', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='数量'),
                    sa.Column('currency', sa.String(length=40), nullable=True, server_default=sqltype.empty_text(),
                              comment='货币'),
                    sa.Column('total_amount', sa.Integer(), nullable=True, server_default=sa.text('0'),
                              comment='总金额'),
                    sa.Column('payment_status', sa.String(length=40),
                              server_default=sa.text("'wait_pay'"), nullable=False, comment='支付状态'),
                    sa.Column('paid_at', sa.DateTime(), nullable=True, server_default=sqltype.invalid_time(),
                              comment='支付完成时间'),
                    sa.Column('pay_failed_at', sa.DateTime(), nullable=True, server_default=sqltype.invalid_time(),
                              comment='支付失败时间'),
                    sa.Column('refunded_at', sa.DateTime(), nullable=True, server_default=sqltype.invalid_time(),
                              comment='退款时间'),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False, comment='创建时间'),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False, comment='更新时间'),
                    sa.PrimaryKeyConstraint('id', name='provider_order_pkey')
                    )
    with op.batch_alter_table('provider_orders', schema=None) as batch_op:
        batch_op.create_index('idx_provider_order_tenant_provider', ['tenant_id', 'provider_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_orders', schema=None) as batch_op:
        batch_op.drop_index('provider_order_tenant_provider_idx')

    op.drop_table('provider_orders')
    # ### end Alembic commands ###
