"""add tool_invoke_model_log

Revision ID: c71211c8f604
Revises: f25003750af4
Create Date: 2024-01-09 11:42:50.664797

"""
import sqlalchemy as sa
from alembic import op

from core.sqltype import UUID, gen_uuid

# revision identifiers, used by Alembic.
revision = 'c71211c8f604'
down_revision = 'f25003750af4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_model_invokes',
                    sa.Column('id', UUID, default=gen_uuid, nullable=False, comment='ID'),
                    sa.Column('user_id', UUID, nullable=False, comment='用户ID'),
                    sa.Column('tenant_id', UUID, nullable=False, comment='租户ID'),
                    sa.Column('provider', sa.String(length=40), nullable=False, comment='提供方'),
                    sa.Column('tool_type', sa.String(length=40), nullable=False, comment='类型'),
                    sa.Column('tool_name', sa.String(length=40), nullable=False, comment='名称'),
                    sa.Column('tool_id', UUID, nullable=False, comment='工具ID'),
                    sa.Column('model_parameters', sa.String(length=2048), nullable=False, comment='模型参数'),
                    sa.Column('prompt_messages', sa.String(length=255), nullable=False, comment='提示消息'),
                    sa.Column('model_response', sa.String(length=2048), nullable=False, comment='模型返回'),
                    sa.Column('prompt_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False,
                              comment='提示token数'),
                    sa.Column('answer_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False,
                              comment='回答token数'),
                    sa.Column('answer_unit_price', sa.Numeric(precision=10, scale=4), nullable=False,
                              comment='回答单价'),
                    sa.Column('answer_price_unit', sa.Numeric(precision=10, scale=7), server_default=sa.text('0.001'),
                              nullable=False, comment='回答价格'),
                    sa.Column('provider_response_latency', sa.Float(), server_default=sa.text('0'), nullable=False,
                              comment='响应延迟'),
                    sa.Column('total_price', sa.Numeric(precision=10, scale=7), nullable=True,
                              server_default=sa.text('0'), comment='总价'),
                    sa.Column('currency', sa.String(length=255), nullable=False, comment='货币'),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False, comment='创建时间'),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False, comment='更新时间'),
                    sa.PrimaryKeyConstraint('id', name='tool_model_invoke_pkey')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tool_model_invokes')
    # ### end Alembic commands ###
