"""add-annotation-reply

Revision ID: e1901f623fd0
Revises: fca025d3b60f
Create Date: 2023-12-12 06:58:41.054544

"""
import sqlalchemy as sa
from alembic import op

from core import sqltype
from core.sqltype import UUID

# revision identifiers, used by Alembic.
revision = 'e1901f623fd0'
down_revision = 'fca025d3b60f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_annotation_hit_histories',
                    sa.Column('id', UUID(), nullable=False, comment='ID'),
                    sa.Column('app_id', UUID(), nullable=False, comment='应用ID'),
                    sa.Column('annotation_id', UUID(), nullable=False, comment='注解ID'),
                    sa.Column('source', sa.String(length=128), nullable=False, comment='来源'),
                    sa.Column('question', sa.String(length=255), nullable=False, comment='问题'),
                    sa.Column('account_id', UUID(), nullable=False, comment='账户ID'),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False, comment='创建时间'),
                    sa.PrimaryKeyConstraint('id', name='app_annotation_hit_histories_pkey')
                    )
    with op.batch_alter_table('app_annotation_hit_histories', schema=None) as batch_op:
        batch_op.create_index('idx_app_annotation_hit_histories_account', ['account_id'], unique=False)
        batch_op.create_index('idx_app_annotation_hit_histories_annotation', ['annotation_id'], unique=False)
        batch_op.create_index('idx_app_annotation_hit_histories_app', ['app_id'], unique=False)

    with op.batch_alter_table('app_model_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annotation_reply', sa.JSON(), nullable=True, comment='回复'))

    with op.batch_alter_table('dataset_collection_bindings', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('type', sa.String(length=40), server_default=sa.text("'dataset'"),
                      nullable=False, comment='类型'))

    with op.batch_alter_table('message_annotations', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('question', sa.String(length=2048), nullable=True, server_default=sqltype.empty_text(),
                      comment='问题'))
        batch_op.add_column(
            sa.Column('hit_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='命中数'))
        batch_op.alter_column('conversation_id',
                              existing_type=UUID(),
                              nullable=True,
                              server_default=sqltype.empty_text())
        batch_op.alter_column('message_id',
                              existing_type=UUID(),
                              nullable=True,
                              server_default=sqltype.empty_text())

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_annotations', schema=None) as batch_op:
        batch_op.alter_column('message_id',
                              existing_type=UUID(),
                              nullable=False)
        batch_op.alter_column('conversation_id',
                              existing_type=UUID(),
                              nullable=False)
        batch_op.drop_column('hit_count')
        batch_op.drop_column('question')

    with op.batch_alter_table('dataset_collection_bindings', schema=None) as batch_op:
        batch_op.drop_column('type')

    with op.batch_alter_table('app_model_configs', schema=None) as batch_op:
        batch_op.drop_column('annotation_reply')

    with op.batch_alter_table('app_annotation_hit_histories', schema=None) as batch_op:
        batch_op.drop_index('app_annotation_hit_histories_app_idx')
        batch_op.drop_index('app_annotation_hit_histories_annotation_idx')
        batch_op.drop_index('app_annotation_hit_histories_account_idx')

    op.drop_table('app_annotation_hit_histories')
    # ### end Alembic commands ###
