"""e08af0a69ccefbb59fa80c778efee300bb780980

Revision ID: e32f6ccb87c6
Revises: a45f4dfde53b
Create Date: 2023-06-06 19:58:33.103819

"""
import sqlalchemy as sa
from alembic import op

from core.sqltype import UUID

# revision identifiers, used by Alembic.
revision = 'e32f6ccb87c6'
down_revision = '614f77cecc48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source_bindings',
                    sa.Column('id', UUID(), nullable=False, comment='ID'),
                    sa.Column('tenant_id', UUID(), nullable=False, comment='租户ID'),
                    sa.Column('access_token', sa.String(length=255), nullable=False, comment='访问令牌'),
                    sa.Column('provider', sa.String(length=255), nullable=False, comment='提供方'),
                    sa.Column('source_info', sa.JSON(), nullable=False, comment='源信息'),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False, comment='创建时间'),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False, comment='更新时间'),
                    sa.Column('disabled', sa.Boolean(), server_default=sa.text('false'), nullable=True,
                              comment='是否禁用'),
                    sa.PrimaryKeyConstraint('id', name='source_binding_pkey')
                    )
    with op.batch_alter_table('data_source_bindings', schema=None) as batch_op:
        batch_op.create_index('idx_source_binding_tenant_id', ['tenant_id'], unique=False)
        # batch_op.create_index('idx_source_info', ['source_info'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_source_bindings', schema=None) as batch_op:
        # batch_op.drop_index('source_info', postgresql_using='gin')
        batch_op.drop_index('source_binding_tenant_id_idx')

    op.drop_table('data_source_bindings')
    # ### end Alembic commands ###
