"""add_anntation_history_message_id

Revision ID: f2a6fc85e260
Revises: 46976cc39132
Create Date: 2023-12-13 11:09:29.329584

"""
import sqlalchemy as sa
from alembic import op

from core import sqltype
from core.sqltype import UUID

# revision identifiers, used by Alembic.
revision = 'f2a6fc85e260'
down_revision = '46976cc39132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_annotation_hit_histories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_id', UUID(), nullable=False,
                                      server_default=sqltype.empty_text(), comment='消息ID'))
        batch_op.create_index('idx_app_annotation_hit_histories_message', ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_annotation_hit_histories', schema=None) as batch_op:
        batch_op.drop_index('app_annotation_hit_histories_message_idx')
        batch_op.drop_column('message_id')

    # ### end Alembic commands ###
